# Generated by Django 4.1.5 on 2023-02-07 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last name')),
                ('plate_nubmer', models.CharField(max_length=32, verbose_name='Plate number')),
                ('veh_type', models.SmallIntegerField(choices=[(1, 'Hatchback'), (2, 'MPV'), (3, 'Pickup'), (4, 'Sedan'), (5, 'Sports'), (6, 'SUV'), (7, 'other')], default=1, verbose_name='Vehicle type')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacity')),
                ('manufacturer', models.CharField(blank=True, max_length=32, verbose_name='Manufacturer')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='Registered time')),
                ('vehicle_info', models.TextField(blank=True, verbose_name='Vehicle info')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Open'), (2, 'Confirmed'), (3, 'Complete')], default=1, verbose_name='Ride status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('start_point', models.CharField(max_length=256, verbose_name='Starting')),
                ('destination', models.CharField(max_length=256, verbose_name='Destination')),
                ('req_arrival_time', models.DateTimeField(help_text='eg. 1970-01-01 00:00', verbose_name='Required Arrival Time')),
                ('passengers', models.PositiveSmallIntegerField(verbose_name='Passengers')),
                ('veh_type', models.SmallIntegerField(choices=[(0, 'Any'), (1, 'Hatchback'), (2, 'MPV'), (3, 'Pickup'), (4, 'Sedan'), (5, 'Sports'), (6, 'SUV'), (7, 'other')], default=0, verbose_name='Vehicle type')),
                ('is_shared', models.SmallIntegerField(choices=[(1, 'No'), (2, 'Yes')], default=False, verbose_name='is shared')),
                ('special_request', models.TextField(blank=True, verbose_name='Special requests')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.driver', verbose_name=' ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_passengers', models.PositiveSmallIntegerField(verbose_name='Sharer passengers')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.ride', verbose_name=' ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' ')),
            ],
        ),
    ]
